"""Turns Snowfakery JSON output into a runnable anonymous-Apex loader.

    python scripts/qdtd/build-load-apex.py

Reads datasets/qdtd/out-foundation.json and out-products.json (produced by
`snowfakery <recipe> --output-format json --output-file <out>`) and writes two
scripts, because anonymous Apex is capped at 32KB and the whole dataset is 39KB:

    scripts/apex/qdtd-load-01-accounts.apex   accounts, contacts, opportunities
    scripts/apex/qdtd-load-02-catalog.apex    products and pricebook entries

Run them in order. The catalog script is independent of the account script.

Why generate Apex rather than load through CumulusCI: the cci path needs the
org's access token handed to a second tool, and the Salesforce CLI now redacts
it. Apex runs inside the org with no token handoff at all. It also keeps the
reference resolution (Contact.AccountId, Opportunity.AccountId) explicit and
visible in the generated file instead of buried in a mapping YAML.

The generated script is idempotent: it deletes its own QDTD- records first and
never touches anything else.
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]

# List prices by the index in the product code (QDTD-HW-3 -> index 3). These
# live here rather than in the recipe because Snowfakery drops __-prefixed
# fields from its output, and the matrix needs specific price *shapes*, not
# random money: whole dollars, three-decimal values, zero, a negative credit,
# and a value that thirds badly for the rounding cases.
PRICE_BY_INDEX = {
    1: "1200", 2: "899.995", 3: "0", 4: "-450", 5: "333.333",
    6: "75.25", 7: "4999", 8: "12.005", 9: "250", 10: "1000",
}
UNICODE_PRICE = "1234.567"


def apex_string(value):
    """Apex string literal - escapes quotes and backslashes, keeps unicode."""
    if value is None:
        return "null"
    s = str(value).replace("\\", "\\\\").replace("'", "\\'")
    return "'" + s + "'"


def list_price_for(product_code):
    if product_code == "QDTD-UNI-1":
        return UNICODE_PRICE
    index = int(product_code.rsplit("-", 1)[1])
    return PRICE_BY_INDEX[index]


def main():
    foundation = json.loads((ROOT / "datasets/qdtd/out-foundation.json").read_text(encoding="utf-8"))
    products = json.loads((ROOT / "datasets/qdtd/out-products.json").read_text(encoding="utf-8"))

    accounts = [r for r in foundation if r["_table"] == "Account"]
    contacts = [r for r in foundation if r["_table"] == "Contact"]
    opportunities = [r for r in foundation if r["_table"] == "Opportunity"]

    out = []
    w = out.append

    w("/**")
    w(" * QDTD foundation data loader - GENERATED by scripts/qdtd/build-load-apex.py")
    w(" * from the Snowfakery recipes in datasets/qdtd/. Do not hand-edit: regenerate.")
    w(" *")
    w(" * Step 02 of specs/quote-document-test-data. Loads accounts, contacts,")
    w(" * opportunities and the product catalogue. Quotes and quote lines are step 03.")
    w(" *")
    w(" * Re-runnable: deletes only records carrying the QDTD- marker, then rebuilds.")
    w(" */")
    w("")
    w("// ---------------------------------------------------------------------------")
    w("// Teardown - strictly by marker. Nothing else is ever touched.")
    w("// ---------------------------------------------------------------------------")
    # Marker lives on Name, not Description: Description is a long text area and
    # SOQL cannot filter one with LIKE (it fails at compile, not at run time).
    w("List<Account> priorAccounts = [SELECT Id FROM Account WHERE Name LIKE 'QDTD-%'];")
    w("if (!priorAccounts.isEmpty()) {")
    w("    delete [SELECT Id FROM SBQQ__Quote__c WHERE SBQQ__Account__c IN :priorAccounts];")
    w("    delete [SELECT Id FROM Opportunity WHERE AccountId IN :priorAccounts];")
    w("    delete priorAccounts;")
    w("}")
    # The catalogue's teardown lives in the catalogue script, not here: this half
    # runs second in practice, and deleting products from it wiped the catalogue
    # the other script had just loaded.
    w("")
    w("// ---------------------------------------------------------------------------")
    w("// Accounts")
    w("// ---------------------------------------------------------------------------")
    w("Map<Integer, Account> accountsByKey = new Map<Integer, Account>();")
    for a in accounts:
        w(
            "accountsByKey.put({key}, new Account(Name = {name}, Industry = {ind}, "
            "BillingStreet = {street}, BillingCity = {city}, BillingPostalCode = {zip}, "
            "BillingCountry = {country}, Phone = {phone}, Description = {desc}));".format(
                key=a["id"], name=apex_string("QDTD- " + a["Name"]), ind=apex_string(a["Industry"]),
                street=apex_string(a["BillingStreet"]), city=apex_string(a["BillingCity"]),
                zip=apex_string(a["BillingPostalCode"]), country=apex_string(a["BillingCountry"]),
                phone=apex_string(a["Phone"]), desc=apex_string(a["Description"]),
            )
        )
    w("insert accountsByKey.values();")
    w("")
    w("// ---------------------------------------------------------------------------")
    w("// Contacts - two per account, primary plus signer")
    w("// ---------------------------------------------------------------------------")
    w("List<Contact> contacts = new List<Contact>();")
    for c in contacts:
        w(
            "contacts.add(new Contact(AccountId = accountsByKey.get({acct}).Id, FirstName = {first}, "
            "LastName = {last}, Email = {email}, Phone = {phone}, Title = {title}, Description = {desc}));".format(
                acct=c["AccountId"], first=apex_string(c["FirstName"]), last=apex_string(c["LastName"]),
                email=apex_string(c["Email"]), phone=apex_string(c["Phone"]),
                title=apex_string(c["Title"]), desc=apex_string(c["Description"]),
            )
        )
    w("insert contacts;")
    w("")
    w("// ---------------------------------------------------------------------------")
    w("// Opportunities - one per account, the parent every quote hangs off")
    w("// ---------------------------------------------------------------------------")
    w("Map<Integer, Opportunity> opportunitiesByKey = new Map<Integer, Opportunity>();")
    for o in opportunities:
        w(
            "opportunitiesByKey.put({key}, new Opportunity(AccountId = accountsByKey.get({acct}).Id, "
            "Name = {name}, StageName = {stage}, CloseDate = Date.valueOf({close}), Amount = {amount}, "
            "Description = {desc}));".format(
                key=o["id"], acct=o["AccountId"], name=apex_string(o["Name"]),
                stage=apex_string(o["StageName"]), close=apex_string(o["CloseDate"]),
                amount=o["Amount"], desc=apex_string(o["Description"]),
            )
        )
    w("insert opportunitiesByKey.values();")
    w("")
    w("// ---------------------------------------------------------------------------")
    w("// Product catalogue - literal, never faked: every grouping in the matrix")
    w("// keys off Family and ProductCode.")
    w("// ---------------------------------------------------------------------------")
    w("List<Product2> products = new List<Product2>();")
    for p in products:
        w(
            "products.add(new Product2(Name = {name}, ProductCode = {code}, Family = {fam}, "
            "IsActive = true, Description = {desc}));".format(
                name=apex_string(p["Name"]), code=apex_string(p["ProductCode"]),
                fam=apex_string(p["Family"]), desc=apex_string(p["Description"]),
            )
        )
    w("insert products;")
    w("")
    w("Map<String, Id> productIdByCode = new Map<String, Id>();")
    w("for (Product2 p : products) { productIdByCode.put(p.ProductCode, p.Id); }")
    w("")
    w("// ---------------------------------------------------------------------------")
    w("// Pricebook entries on the standard pricebook.")
    w("//")
    w("// PricebookEntry.UnitPrice cannot be negative, so the credit product is listed")
    w("// at its absolute value here; the negative amount is applied on the quote line")
    w("// in step 03, which is where the generator reads it from anyway.")
    w("// ---------------------------------------------------------------------------")
    w("Id standardPricebookId = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1].Id;")
    w("List<PricebookEntry> entries = new List<PricebookEntry>();")
    for p in products:
        price = list_price_for(p["ProductCode"])
        w(
            "entries.add(new PricebookEntry(Pricebook2Id = standardPricebookId, "
            "Product2Id = productIdByCode.get({code}), UnitPrice = Math.abs({price}), "
            "IsActive = true, UseStandardPrice = false));".format(
                code=apex_string(p["ProductCode"]), price=price,
            )
        )
    w("insert entries;")
    w("")
    w("System.debug('QDTD catalogue loaded: products=' + products.size()")
    w("    + ' pricebookEntries=' + entries.size());")
    w("")

    # Anonymous Apex is capped at 32KB and the full dataset is ~39KB, so the
    # output splits at the natural seam: nothing in the catalogue references an
    # account, which makes the two halves independent.
    # Anonymous Apex is capped at 32KB and the full dataset is ~39KB, so the
    # output splits at the natural seam: nothing in the catalogue references an
    # account, which makes the two halves independent.
    text = "\n".join(out)
    marker = "// Product catalogue"
    head, tail = text.split(marker, 1)

    accounts_script = (
        head
        + "System.debug('QDTD accounts loaded: accounts=' + accountsByKey.size()\n"
        + "    + ' contacts=' + contacts.size() + ' opportunities=' + opportunitiesByKey.size());\n"
    )

    catalog_script = "\n".join([
        "/**",
        " * QDTD product catalogue loader - GENERATED by scripts/qdtd/build-load-apex.py.",
        " * Second half of step 02. Independent of qdtd-load-01-accounts.apex.",
        " */",
        "",
        "// Subscriptions hold a lookup to these products. Deleting the products",
        "// first nulls that lookup, which orphans them: the step-03 teardown finds",
        "// its own subscriptions BY product code, so orphans survive every later",
        "// rerun and accumulate. Removing them here, while the link still exists,",
        "// keeps every fixture record reachable from the marker that owns it.",
        "delete [SELECT Id FROM SBQQ__Subscription__c WHERE SBQQ__Product__r.ProductCode LIKE 'QDTD-%'];",
        "delete [SELECT Id FROM PricebookEntry WHERE Product2.ProductCode LIKE 'QDTD-%'];",
        "delete [SELECT Id FROM Product2 WHERE ProductCode LIKE 'QDTD-%'];",
        "",
        marker,
    ]) + tail

    first = ROOT / "scripts/apex/qdtd-load-01-accounts.apex"
    second = ROOT / "scripts/apex/qdtd-load-02-catalog.apex"
    first.write_text(accounts_script, encoding="utf-8")
    second.write_text(catalog_script, encoding="utf-8")

    print("wrote {} ({} bytes) - {} accounts, {} contacts, {} opportunities".format(
        first.relative_to(ROOT), len(accounts_script), len(accounts), len(contacts), len(opportunities)))
    print("wrote {} ({} bytes) - {} products".format(
        second.relative_to(ROOT), len(catalog_script), len(products)))


if __name__ == "__main__":
    main()
